### ISSUE TITLE
Simple Read returns inconsistent results

### ISSUE THREAD

**Issue by abronan** [MagnusS/irmin-go#3]
Hi @MagnusS,

Integrating Irmin to [libkv](https://github.com/docker/libkv). It seems like the simple Read fails the test case used for other stores like `etcd/consul/zookeeper` which checks the value after being updated by a Watch event.

Sequence of actions in the test is:
- Write key `foo` with value `foo`
- Trigger an update every `250ms` (for `1s`) by writing value `bar` for key `foo`
- Check the value (Read) after we receive an event from the **Watch** (should match value `bar`)
- _(At the end: check for the number of events triggered which is 4)_

Randomly the test will fail on the Read after the first watch event supposed to notify a value update, because the Read returns the old value (`foo`) instead of the new one.

Is this is an expected behavior (in terms of consistency)?

Some more infos:

``` bash
$ uname -a
Linux archbox 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
```

``` bash
$ irmin --version
0.10.0
```

I start the store locally for testing purposes using:

```
$ irmin init -d -v --root /tmp/irmin/base -a http://:6744
```

Thank you!

**Comment by MagnusS** [comment]
Hm - a call to `read` should always return the new value after the `watch` event has been received. Could you capture the HTTP traffic between the test and irmin? It might make it easier to determine where the bug is.

**Comment by MagnusS** [comment]
I tried to write the same test, but I'm unable to reproduce the problem. Is this test similar to the one you have? 

https://github.com/MagnusS/irmin-go/blob/master/irmin/http_test.go#L237

**Comment by abronan** [comment]
Test look similar, I just do the updates in a separate goroutine. We also have this particularity in libkv where we return the old value through the channel first. But this does not hinder the test as the value is seen as updated on the second event.

See https://github.com/docker/libkv/blob/master/testutils/utils.go#L144 (Test is randomly failing on this line, saying that it returns the old value even after the watch event is being fired a second time which supposedly would show the updated value).

Falling back to a simple test (not sending back the first value on the watch and doing a simple check after the first watch event is being fired) gives me the same result.

Pushed the experimental irmin branch on libkv [here](https://github.com/abronan/libkv/blob/add_irmin_support/store/irmin/irmin.go).

Will try to investigate looking at the HTTP traffic to see what's going on (might be an issue on my side), thanks for looking at it @MagnusS!
