### ISSUE TITLE
Panic: `Server returned an error:` on WatchPath

### ISSUE THREAD

**Issue by abronan** [MagnusS/irmin-go#4]
Executing `WatchPath` leads to a `panic: Server returned an error:`

Here is the Stack trace executing the code in the example folder:

```
$ go run watch_path.go
version: 0.10.0
Watching /
(run examples/views/views.go example to test)
panic: Server returned an error: 

goroutine 1 [running]:
main.main()
    /home/abronan/go/src/github.com/MagnusS/irmin-go/examples/watch_path.go:49 +0x53e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 18 [IO wait]:
net.runtime_pollWait(0x7fca3ccc9580, 0x72, 0xc82000a230)
    /usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82005c290, 0x72, 0x0, 0x0)
    /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82005c290, 0x0, 0x0)
    /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82005c230, 0xc8200bc000, 0x1000, 0x1000, 0x0, 0x7fca3ccc4050, 0xc82000a230)
    /usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200b6000, 0xc8200bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/lib/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7fca3b481000, 0xc8200b6000, 0xc8200b0058, 0xc8200bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/lib/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8200b2040, 0xc8200bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8200ba000)
    /usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8200ba000, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/lib/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200b0000)
    /usr/lib/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/lib/go/src/net/http/transport.go:685 +0xc78

goroutine 19 [select]:
net/http.(*persistConn).writeLoop(0xc8200b0000)
    /usr/lib/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/lib/go/src/net/http/transport.go:686 +0xc9d
exit status 2
```

I'm seeing this executing the example but also when calling it in my code [here](https://github.com/abronan/libkv/blob/add_irmin_support/store/irmin/irmin.go#L216)

Interesting to note is that there is no issue with the simple Watch, it works just fine.

**Comment by MagnusS** [comment]
It seems that the `watch-rec` command used by `WatchPath` is only available in Irmin master. You can install the master branch with `opam pin add irmin --dev`, but it would be better with a proper release that included it :-) /cc @samoht

**Comment by samoht** [comment]
I'll make a new release of Irmin later today.

**Comment by samoht** [comment]
But would be great if the bindings would check the Irmin version and display a better error message :-)

**Comment by MagnusS** [comment]
Yes, there's a bug in irmin-go here - the error message should have shown that the command was unsupported, which is what Irmin reports. Version checks are a good idea, but wouldn't have helped here though, as the master and latest release have the same version number :-)

**Comment by samoht** [comment]
release done, should appear in opam soon so that `opam update` will pick the new `0.10.1` version.

**Comment by abronan** [comment]
Updated to `0.10.1` and works like a charm :)

Thanks @MagnusS and @samoht!

Closing this one as there is now an issue opened for a better error check.
